# Generated by Django 2.0.2 on 2018-04-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobdetails_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobdetails',
            new_name='Job',
        ),
    ]
