# Generated by Django 2.0.2 on 2018-03-23 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='web',
            field=models.CharField(blank=True, max_length=2000, validators=[django.core.validators.URLValidator()]),
        ),
    ]
