# Generated by Django 2.0.2 on 2018-04-04 23:16

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20180405_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to=''),
        ),
    ]
