# Generated by Django 2.0.2 on 2018-03-23 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180323_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='web',
            field=models.TextField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
