# Generated by Django 2.0.2 on 2018-03-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
    ]
