# Generated by Django 2.0.2 on 2018-03-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
